# Generated by Django 2.2.6 on 2019-10-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work', models.CharField(default='None', max_length=200)),
                ('WorkText', models.CharField(default='None', max_length=200)),
                ('Date_Create', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(default='None', max_length=200)),
                ('Skill_Text', models.CharField(default='None', max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='default/upload_image/')),
                ('Date_Create', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Visitor_Email', models.CharField(default='None', max_length=200)),
                ('Date_Create', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
